import LegalLayout, { Section, P, List, Anchor } from './LegalLayout';
import { COMPANY } from '../lib/site';

const TermsOfService = () => {
  return (
    <LegalLayout title="Terms of Service" updated="October 2, 2026">
      <Section title="1. Agreement to These Terms">
        <P>
          These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of the Paqt
          website, waitlist, and subscription service (collectively, the &ldquo;Service&rdquo;),
          operated by {COMPANY.name} (&ldquo;Paqt,&rdquo; &ldquo;we,&rdquo; &ldquo;our,&rdquo; or
          &ldquo;us&rdquo;). By accessing or using the Service, you agree to be bound by these
          Terms. If you do not agree, please do not use the Service.
        </P>
      </Section>
      <Section title="2. Eligibility and Accounts">
        <P>You must be at least 18 years old to use the Service.</P>
        <P>
          When you join our waitlist or create an account, you agree to provide accurate, current,
          and complete information and to keep that information up to date. You are responsible for
          maintaining the confidentiality of your account credentials and for all activity that
          occurs under your account.
        </P>
      </Section>
      <Section title="3. Use of the Service">
        <P>
          The Service provides contract drafting, analysis, and related tools. The Service is
          currently offered on a waitlist basis and, when made available, under a paid subscription.
        </P>
        <P>You agree not to misuse the Service, including by:</P>
        <List
          items={[
            'Using the Service for any unlawful purpose or in violation of applicable laws, including laws of India;',
            'Attempting to interfere with, disrupt, or gain unauthorized access to the Service, its servers, or connected networks;',
            'Reverse engineering, decompiling, or scraping the Service or its content;',
            'Using the Service to generate or distribute fraudulent, defamatory, or infringing materials.',
          ]}
        />
      </Section>
      <Section title="4. Subscriptions, Billing, and Payments">
        <P>
          Paid features of the Service are provided on a subscription basis. Subscription fees are
          billed automatically at the start of each billing cycle using the payment method you
          provided, until you cancel your subscription.
        </P>
        <P>
          All fees are expressed in Indian Rupees (INR) unless stated otherwise. Applicable taxes,
          including GST, may be added to the fees. We use third-party payment gateways to process
          payments; your payment information is handled by the gateway and is not stored by us.
        </P>
      </Section>
      <Section title="5. Cancellation Policy">
        <P>
          You may cancel your subscription at any time. When you cancel, your subscription remains
          active until the end of the billing period you have already paid for, and you will not be
          charged again at the end of that period. To continue using the Service after your current
          tenure ends, you must purchase a new subscription. Please review our{' '}
          <Anchor to="/cancellation">Cancellation &amp; Refund Policy</Anchor> for full details.
        </P>
      </Section>
      <Section title="6. Refund Policy">
        <P>
          Fees paid for an active subscription period are non-refundable, except as required by
          applicable law, including the Indian Consumer Protection Act, 2019. We do not provide
          prorated refunds for partially used subscription periods. See our{' '}
          <Anchor to="/cancellation">Cancellation &amp; Refund Policy</Anchor> and{' '}
          <Anchor to="/privacy-policy">Privacy Policy</Anchor> for more information.
        </P>
      </Section>
      <Section title="7. Intellectual Property">
        <P>
          The Service, including its software, design, text, graphics, and branding, is owned by
          Paqt or its licensors and is protected by applicable intellectual property laws. You may
          not copy, modify, distribute, or create derivative works from the Service without our
          prior written consent. Your documents and the content you create with the Service remain
          yours.
        </P>
      </Section>
      <Section title="8. Disclaimer of Warranties">
        <P>
          The Service is provided on an &ldquo;as is&rdquo; and &ldquo;as available&rdquo; basis,
          including during any beta or early-access stages. To the maximum extent permitted by law,
          we make no warranties, express or implied, regarding the availability, reliability, or
          fitness of the Service for a particular purpose. Output generated by the Service is for
          informational assistance only and does not constitute legal advice. You should have legal
          documents reviewed by a qualified professional.
        </P>
      </Section>
      <Section title="9. Limitation of Liability">
        <P>
          To the maximum extent permitted by law, Paqt shall not be liable for any indirect,
          incidental, special, consequential, or punitive damages, or for any loss of profits,
          data, or goodwill, arising out of or relating to your use of the Service. Our total
          aggregate liability shall not exceed the amounts paid by you to us in the twelve (12)
          months preceding the claim.
        </P>
      </Section>
      <Section title="10. Indemnification">
        <P>
          You agree to indemnify and hold harmless Paqt, its officers, directors, employees, and
          agents from any claims, liabilities, damages, and expenses (including reasonable attorney
          fees) arising out of your use of the Service or your violation of these Terms or
          applicable law.
        </P>
      </Section>
      <Section title="11. Changes to These Terms">
        <P>
          We may update these Terms from time to time. Material changes will be notified by posting
          the revised Terms on this page with an updated &ldquo;Last updated&rdquo; date. Continued
          use of the Service after changes take effect constitutes acceptance of the revised Terms.
        </P>
      </Section>
      <Section title="12. Governing Law and Disputes">
        <P>
          These Terms are governed by the laws of India. Any disputes arising out of or relating to
          these Terms shall be subject to the exclusive jurisdiction of the courts at [City of
          registered office], India.
        </P>
      </Section>
      <Section title="13. Contact Us">
        <P>
          For questions about these Terms, contact us at:{' '}
          <Anchor to={`mailto:${COMPANY.email}`}>{COMPANY.email}</Anchor>, {COMPANY.phoneIndia}, or
          at our registered office: {COMPANY.address}.
        </P>
      </Section>
    </LegalLayout>
  );
};

export default TermsOfService;